// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShop.Services.Catalog.API.Infrastructure;

namespace Catalog.API.Infrastructure.CatalogMigrations {
    [DbContext(typeof(CatalogContext))]
    [Migration("20251001215646_Initial")]
    partial class Initial {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("catalog_brands_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("catalog_items_hilo")
                .IncrementsBy(10);

            modelBuilder.HasSequence("catalog_types_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("eShop.Services.Catalog.API.Model.CatalogBrand", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("ID"), "catalog_brands_hilo");

                b.Property<string>("Brand")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("ID");

                b.ToTable("CatalogBrands");
            });

            modelBuilder.Entity("eShop.Services.Catalog.API.Model.CatalogItem", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("ID"), "catalog_items_hilo");

                b.Property<int>("CatalogBrandID")
                    .HasColumnType("int");

                b.Property<int>("CatalogTypeID")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("PictureFileName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("ID");

                b.HasIndex("CatalogBrandID");

                b.HasIndex("CatalogTypeID");

                b.ToTable("CatalogItems");
            });

            modelBuilder.Entity("eShop.Services.Catalog.API.Model.CatalogType", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("ID"), "catalog_types_hilo");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("ID");

                b.ToTable("CatalogTypes");
            });

            modelBuilder.Entity("eShop.Services.Catalog.API.Model.CatalogItem", b => {
                b.HasOne("eShop.Services.Catalog.API.Model.CatalogBrand", "CatalogBrand")
                    .WithMany()
                    .HasForeignKey("CatalogBrandID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("eShop.Services.Catalog.API.Model.CatalogType", "CatalogType")
                    .WithMany()
                    .HasForeignKey("CatalogTypeID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CatalogBrand");

                b.Navigation("CatalogType");
            });
#pragma warning restore 612, 618
        }
    }
}
