// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShop.Services.Ordering.Infrastructure;

namespace Ordering.API.Infrastructure.OrderingMigrations {
    [DbContext(typeof(OrderingContext))]
    partial class OrderingContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("buyer_hilo", "Ordering")
                .IncrementsBy(10);

            modelBuilder.HasSequence("order_hilo", "Ordering")
                .IncrementsBy(10);

            modelBuilder.HasSequence("orderitems_hilo", "Ordering")
                .IncrementsBy(10);

            modelBuilder.HasSequence("payment_hilo", "Ordering")
                .IncrementsBy(10);

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.BuyerAggregate.Buyer", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("ID"), "buyer_hilo", "Ordering");

                b.Property<string>("IdentityGUID")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("ID");

                b.HasIndex("IdentityGUID")
                    .IsUnique();

                b.ToTable("Buyers", "Ordering");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.BuyerAggregate.CardType", b => {
                b.Property<int>("ID")
                    .HasColumnType("int")
                    .HasDefaultValue(1);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("ID");

                b.ToTable("CardTypes", "Ordering");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.BuyerAggregate.PaymentMethod", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("ID"), "payment_hilo", "Ordering");

                b.Property<int>("BuyerID")
                    .HasColumnType("int");

                b.Property<string>("alias")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)")
                    .HasColumnName("Alias");

                b.Property<string>("cardHolderName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)")
                    .HasColumnName("CardHolderName");

                b.Property<string>("cardNumber")
                    .IsRequired()
                    .HasMaxLength(19)
                    .HasColumnType("nvarchar(19)")
                    .HasColumnName("CardNumber");

                b.Property<int>("cardTypeID")
                    .HasColumnType("int")
                    .HasColumnName("CardTypeID");

                b.Property<DateTime>("expirationDate")
                    .HasMaxLength(25)
                    .HasColumnType("datetime2")
                    .HasColumnName("ExpirationDate");

                b.Property<string>("securityNumber")
                    .IsRequired()
                    .HasMaxLength(4)
                    .HasColumnType("nvarchar(4)")
                    .HasColumnName("SecurityNumber");

                b.HasKey("ID");

                b.HasIndex("BuyerID");

                b.HasIndex("cardTypeID");

                b.ToTable("PaymentMethods", "Ordering");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.OrderAggregate.Order", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("ID"), "order_hilo", "Ordering");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("OrderStatusID")
                    .HasColumnType("int");

                b.Property<int?>("buyerID")
                    .HasColumnType("int")
                    .HasColumnName("BuyerID");

                b.Property<bool>("isDraft")
                    .HasColumnType("bit");

                b.Property<DateTime>("orderDate")
                    .HasColumnType("datetime2")
                    .HasColumnName("OrderDate");

                b.Property<int?>("paymentMethodID")
                    .HasColumnType("int")
                    .HasColumnName("PaymentMethodID");

                b.HasKey("ID");

                b.HasIndex("OrderStatusID");

                b.HasIndex("buyerID");

                b.HasIndex("paymentMethodID");

                b.ToTable("Orders", "Ordering");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.OrderAggregate.OrderItem", b => {
                b.Property<int>("ID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("ID"), "orderitems_hilo", "Ordering");

                b.Property<int?>("OrderID")
                    .HasColumnType("int");

                b.Property<int>("ProductID")
                    .HasColumnType("int");

                b.Property<decimal>("discount")
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("Discount");

                b.Property<string>("pictureURL")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("PictureURL");

                b.Property<string>("productName")
                    .HasColumnType("nvarchar(max)")
                    .HasColumnName("ProductName");

                b.Property<decimal>("unitPrice")
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("UnitPrice");

                b.Property<int>("units")
                    .HasColumnType("int")
                    .HasColumnName("Units");

                b.HasKey("ID");

                b.HasIndex("OrderID");

                b.ToTable("OrderItems", "Ordering");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.OrderAggregate.OrderStatus", b => {
                b.Property<int>("ID")
                    .HasColumnType("int")
                    .HasDefaultValue(1);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("ID");

                b.ToTable("OrderStatuses", "Ordering");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Infrastructure.Idempotency.ClientRequest", b => {
                b.Property<Guid>("GUID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("DateTime")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("GUID");

                b.ToTable("ClientRequests", "Idempotency");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.BuyerAggregate.PaymentMethod", b => {
                b.HasOne("eShop.Services.Ordering.Domain.Model.BuyerAggregate.Buyer", null)
                    .WithMany("PaymentMethods")
                    .HasForeignKey("BuyerID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("eShop.Services.Ordering.Domain.Model.BuyerAggregate.CardType", "CardType")
                    .WithMany()
                    .HasForeignKey("cardTypeID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("CardType");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.OrderAggregate.Order", b => {
                b.HasOne("eShop.Services.Ordering.Domain.Model.OrderAggregate.OrderStatus", "OrderStatus")
                    .WithMany()
                    .HasForeignKey("OrderStatusID");

                b.HasOne("eShop.Services.Ordering.Domain.Model.BuyerAggregate.Buyer", null)
                    .WithMany()
                    .HasForeignKey("buyerID");

                b.HasOne("eShop.Services.Ordering.Domain.Model.BuyerAggregate.PaymentMethod", null)
                    .WithMany()
                    .HasForeignKey("paymentMethodID")
                    .OnDelete(DeleteBehavior.Restrict);

                b.OwnsOne("eShop.Services.Ordering.Domain.Model.OrderAggregate.Address", "Address", b1 => {
                    b1.Property<int>("OrderID")
                        .HasColumnType("int");

                    b1.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b1.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b1.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b1.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b1.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b1.HasKey("OrderID");

                    b1.ToTable("Orders", "Ordering");

                    b1.WithOwner()
                        .HasForeignKey("OrderID");
                });

                b.Navigation("Address");

                b.Navigation("OrderStatus");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.OrderAggregate.OrderItem", b => {
                b.HasOne("eShop.Services.Ordering.Domain.Model.OrderAggregate.Order", null)
                    .WithMany("OrderItems")
                    .HasForeignKey("OrderID");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.BuyerAggregate.Buyer", b => {
                b.Navigation("PaymentMethods");
            });

            modelBuilder.Entity("eShop.Services.Ordering.Domain.Model.OrderAggregate.Order", b => {
                b.Navigation("OrderItems");
            });
#pragma warning restore 612, 618
        }
    }
}
