// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShop.BuildingBlocks.IntegrationEventLogEF;

namespace Catalog.API.Infrastructure.IntegrationEventMigrations {
    [DbContext(typeof(IntegrationEventLogContext))]
    partial class IntegrationEventLogContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eShop.BuildingBlocks.IntegrationEventLogEF.IntegrationEventLogEntry", b => {
                b.Property<Guid>("EventID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreationDateTime")
                    .HasColumnType("datetime2");

                b.Property<string>("EventTypeName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("State")
                    .HasColumnType("int");

                b.Property<int>("TimesSent")
                    .HasColumnType("int");

                b.Property<string>("TransactionID")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("EventID");

                b.ToTable("IntegrationEventLogs", "Integration");
            });
#pragma warning restore 612, 618
        }
    }
}
